@startuml UML Jeu du Petit Bac - Cas d'utilisation
    left to right direction
    skinparam packageStyle rectangle
    skinparam linetype polyline
    skinparam linetype ortho

    actor "Joueur" as Joueur
    agent "Système de jeu" as System

    rectangle "Jeu du Petit Bac" {

        usecase "Créer une partie" as UC1
        usecase "Rejoindre une partie" as UC2 #palegreen;line:green;line.dashed;text:green
        usecase "Choisir les catégories" as UC3
        usecase "Générer une lettre aléatoire" as UC4
        usecase "Saisir les réponses" as UC5
        usecase "Annoncer Stop" as UC6 
        usecase "Arrêter le chronomètre" as UC7
        usecase "Valider les réponses" as UC8
        usecase "Calculer les points" as UC9
        usecase "Afficher le score" as UC10
        usecase "Gérer les paramètres" as UC11

        Joueur -- (UC1)
        Joueur -- (UC2)
        Joueur -- (UC5)
        Joueur -- (UC6)
        Joueur -[norank]- (UC10)
        Joueur -- (UC11)

        (UC1) --> (UC3) : <<include>>
        (UC1) --> (UC4) : <<include>>
        (UC6) --> (UC7)
        (UC5) --> (UC8)
        (UC8) --> (UC9)
        (UC9) --> (UC10)

        System -- (UC4)
        System -- (UC7)
        System -- (UC8)
        System -- (UC9)
        System -- (UC10)
    }

  @enduml